name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup V
        run: |
          git clone --depth=1 https://github.com/vlang/v v && cd v
          make && ./v symlink && cd ..
      - name: Fmt
        run:  ./v fmt -verify .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup V
        run: |
          git clone --depth=1 https://github.com/vlang/v v && cd v
          make && ./v symlink && cd ..
      - name: Test
        run: ./v test .
  build-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup V
        run: |
          git clone --depth=1 https://github.com/vlang/v v && cd v
          make && ./v symlink && cd ..
      - name: Build examples
        run: ./v examples/hello_world.v
